name: release

on:
  push:
    branches:
      - "master"
    tags:
      - "!*"

jobs:
  release:
    runs-on: [self-hosted]
    container: node:latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "${{ github.event.pusher.email }"
      - run: git config --global user.name "${{ github.event.pusher.name }"
      - run: yarn --frozen-lockfile
      - run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: git push origin --follow-tags
