name: release

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: git config --global user.email "${{ github.event.pusher.email }}"
      - run: git config --global user.name "${{ github.event.pusher.name }}"
      - run: yarn standard-version
      - uses: ad-m/github-push-action@master
        with:
          tags: true
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
